### ISSUE TITLE
codesandbox example

### ISSUE THREAD

**Issue by rpateld** [Esri/screenshot-widget#8]
This is a great component. 
Can you please show the working codesandbox example, please?

**Comment by rslibed** [comment]
Here's a sample app which uses the Screenshot widget: https://webapps.maps.arcgis.com/apps/InteractiveLegend/index.html?appid=8a242fc27b8e4d91b9b2fa076302702f

**Comment by rslibed** [comment]
Closing issue. Reopen if needed.
